apiVersion: v1
kind: Service
metadata:
  name: {{ include "node-k8s-loadtest.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "node-k8s-loadtest.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
    - protocol: TCP
      port: {{ .Values.debug.port }}
      targetPort: {{ .Values.debug.targetPort }}
