apiVersion: v1
kind: Service
metadata:
  name: { { include "node-k8s-loadtest.fullname" . } }
spec:
  type: LoadBalancer
  selector:
    app: { { include "node-k8s-loadtest.name" . } }
  ports:
    - protocol: TCP
      port: { { .Values.service.port } }
      targetPort: 3000
