apiVersion: v1
kind: Service
metadata:
  name: node-k8s-loadtest-service
spec:
  type: LoadBalancer
  selector:
    app: node-k8s-loadtest
  ports:
    - name: application
      protocol: TCP
      port: 3000
      targetPort: 3000
    - name: debug
      protocol: TCP
      port: 9229
      targetPort: 9229
