resources:
  - k8s-deployment.yaml
  - k8s-service.yaml

images:
  - name: node-k8s-loadtest
    newName: nbukhari/node-k8s-loadtest
    newTag: latest

replicas:
  - name: node-k8s-loadtest
    count: 1
