resources:
- k8s-deployment.yaml
- k8s-service.yaml
images:
- name: node-k8s-loadtest
  newName: nbukhari/node-k8s-loadtest
  newTag: latest
replicas:
- count: 1
  name: node-k8s-loadtest
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- path: resources-patch.yaml
