apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-k8s-loadtest
spec:
  template:
    spec:
      containers:
        - name: node-k8s-loadtest
          resources:
            requests:
              cpu: "500m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "512Mi"
          env:
            - name: WORKER_THREADS
              value: "4"
